import Head from "next/head";
import { useEffect } from "react";
import { Inter, Source_Code_Pro } from "@next/font/google";

import { EditorLine } from "../components/EditorLine";

import { execBinding } from "../javascript/keybindings";
import styles from "../styles/Blank.module.css";
import { Editor } from "../components/Editor";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  useEffect(() => {
    document.addEventListener("keydown", execBinding);

    return () => {
      document.removeEventListener("keydown", execBinding);
    };
  });

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>RUSTY</h1>
        <div className="editor" id="editor">
            <Editor text="Hello World\nprint('hello world!')" />
            {/* <div className="editor-gutter">
                 <div className="editor-line-gutter">
                    <div className="editor-line-gutter-symbol">⬤</div>
                    <div className="editor-line-number">1</div>
                </div>
            </div>
            <div className="editor-text" contentEditable="true" spellCheck="false">
                <EditorLine lineNumber={1} text="First line" gutter="⚠" />
                <EditorLine lineNumber={2} text="print('hello world!')" gutter="⬤" />
            </div> */}
        </div>
      </main>
    </>
  );
}
