import Head from "next/head";
import { useEffect } from "react";
import { Inter, Source_Code_Pro } from "@next/font/google";

import { execBinding } from "../javascript/keybindings";
import { Editor } from "../components/Editor";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {

  //? Add listeners for keyboard input
  useEffect(() => {
    document.addEventListener("keydown", execBinding);

    return () => {
      document.removeEventListener("keydown", execBinding);
    };
  });

  const editorText = `func print() -> String {
    let data: &str = "Some Data";
}`;

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="editor" id="editor">
        <Editor text={editorText} />
      </div>
    </>
  );
}
